# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5973879f4c7df6e0162b9a1404d8e1c3b34f0016fd3759ef3b03edc39f9108f35bba6456eb9e1adb595a064cf9321804b0dddb8ac07a9c285863abcca46e41ef

test:
  secret_key_base: 7cf1511df2aefb33e3e9a9dac0b61028ea9302053427d71137a4b4387d16633deb3443dde9435783a0502033d2071366e13803e39e5cfcace438eb280ce7664a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
